import re,json,collections,sys,unicodedata
sys.path.insert(0,'/workspace/enem_multi'); from load import *
def norm(s): return unicodedata.normalize('NFD',s.lower()).encode('ascii','ignore').decode()
def L(s): return [w.replace('_',' ') for w in s.split()]
LEX={
'BIO':L("celula celular dna rna gene genes genetic cromossom proteina enzima organismo especie ecossistem cadeia_alimentar teia_alimentar populac evoluc evolutiv selecao_natural fotossintese respiracao_celular virus bacteria fungo parasit doenca vacina sangue hormonio orgao tecido planta vegeta animal animais inseto mosquito ecolog biodiversidade bioma mutac heranca alelo fenotip genotip mitocondri membrana imun anticorpo neuron digest reproduc embriao larva predador presa mamifer aves peixe anfibi reptil microrganism infecc sintoma paciente saude metabol insulina cloroplast seres_vivos ser_vivo nicho habitat poliniz semente fruto flor raiz folha transgenic clonag sexuad hereditar darwin lamarck adaptac fossil vetor transmissao dengue malaria protozoar verme gestac cancer tumor anemia vitamina nutric amido abelha arvore floresta mangue caatinga cerrado biotecnolog ribossom citoplasma mitose meiose gameta zigoto feto placenta ovulo espermatozoide medula figado rim pulm coracao cerebro musculo osso pele estomago intestino eutrofiz decompositor sucessao_ecologica leguminos hospedeiro contamina epidemi celulose fotossintet trofic biolog organism"),
'QUI':L("reacao reacoes quimic molecul atomo atomic ligacao acido acida acidez basic ph sal sais solucao solucoes concentrac mol mols molar estequiometr oxidac oxidant redutor eletrolis pilha bateria combustao entalpia exotermic endotermic cinetica_quimica equilibrio_quimico catalis organic hidrocarbonet polimer isomer alcool eter ester cetona aldeido amina amida carboxil funcao_organica funcoes_organicas titulac solubil precipit ion ions cation anion g/mol mol/l formula_estrutural isotop tabela_periodica metal metais sodio cloro enxofre separacao_de_mistura destilac filtrac decantac sabao detergente gasolina etanol metanol oxigenio hidrogenio co2 h2o naoh hcl nacl caco3 h2so4 nh3 ch4 so2 no2 oxido hidroxido eletrolit eletrodo anodo catodo corrosao ferrugem soluto solvente diluic coloid neutraliz indicador fenolftaleina reagente rendimento pureza balancea polaridade apolar intermolecular ponte_de_hidrogenio radica grupo_funcional cadeia_carbonica benzeno aromatic plastico biodiesel triglicer saponific esterific fermentac hidrolise ozonio chuva_acida calcario cimento minerio aluminio cobre zinco ferro chumbo mercurio potencial_de_reducao eletroquimic galvaniz carbonato sulfat nitrato fosfat amonia amonio nox massa_molar elemento_quimico eletrons_de_valencia lixivia cristal"),
}
def tokens(q): return norm(' '.join([q['context'] or '',q['alternativesIntroduction'] or '']+[a['text'] or '' for a in q['alternatives']]))
RX={}
def score(t,lex):
    s=0
    for w in lex:
        if w not in RX: RX[w]=re.compile(r'(?<![a-z0-9])'+re.escape(w)+(r'(?![a-z0-9])' if len(w)<=4 else ''))
        s+=len(RX[w].findall(t))
    return s
LEX['GEO']=L("geografia geografico espaco_urbano espacializ zona_rural conurbac verticaliz periferi territorial regionaliz agroindustr fronteira_agricola uso_do_solo clima climatic relevo solo solos bacia_hidrografica hidrografi rio rios urbaniz urbano urbana metropol migrac migrant demografi natalidade mortalidade envelhecimento agricultur agronegocio agropecuari latifundi agrari reforma_agraria globaliz industrializ mapa mapas escala cartograf latitude longitude fuso coordenada vegetac bioma desmatamento erosao chuva chuvas precipitac el_nino massas_de_ar aquifero petroleo transporte rodovi ferrovi fronteira geopolitic otan bloco_economico mercosul uniao_europeia favela segregac exodo_rural commodit impacto_ambiental aquecimento_global efeito_estufa poluic rocha intemperismo tectonic placas terremoto vulcao geomorfolog paisagem espaco_geografico meio_tecnico trabalho_rural campo amazonia cerrado caatinga semiarido semi-arido seca hidreletric matriz_energetica recursos_naturais desertific mineracao minerio oceano litoral costeir planalto planicie montanha cordilheira continente geograf ambiental ambientais sustentavel logistic multinacional transnacional desigualdade_regional bacia lavoura soja gado pecuaria monocultura irrigac reservatorio barragem")
LEX['HIS']=L("seculo imperio imperial colonia colonial colonizac escravid escravo escravos escravizad republica revoluc rei monarquia idade_media medieval feudal ditadura militar getulio vargas independencia grecia grego gregos roma romano romanos igreja cristianismo cristao renascimento iluminismo absolutismo abolic quilombo jesuita constituic estado_novo guerra guerras nazis fascis sovietic comunis portugues portugueses coroa senhor senhores engenho canavieiro cafe cafeicultor oligarqui coronel imigrante operari greve sindicat abolicionis inconfidencia burguesia antigo_regime napoleao cruzada mercantilis metropole_colonial vice-rei dom_pedro imperador regencia proclamac golpe ai-5 redemocratizac anistia egipcio mesopotamia historiador historia historic documento_historico periodo fotografia_de")
LEX['FIL']=L("filosof filosofo platao aristoteles kant descartes hobbes locke rousseau marx weber durkheim etica moral razao conhecimento verdade virtude alma sociedade cultura ideologia alienac nietzsche socrates maquiavel foucault bauman hegel sartre arendt habermas adorno bourdieu montesquieu pensamento sujeito liberdade justica felicidade metafisica epistemolog estetica politica_ conceito religiao religios crenca identidade genero racismo movimento_social direitos cidadania democracia")
