from classify import L
TOPICOS={
'biologia':[
 ('Ecologia e Meio Ambiente', L("ecossistem cadeia_alimentar teia_alimentar trofic ecolog biodiversidade bioma populac predador presa nicho habitat sucessao_ecologica decompositor eutrofiz desmatamento poluic ambiental ambientais impacto mangue cerrado caatinga floresta mata_atlantica amazonia ciclo_do_carbono ciclo_do_nitrogenio ciclo_biogeoquimico efeito_estufa aquecimento_global especie_invasora especies_exoticas extincao conservac reciclag lixo esgoto agrotoxic pesticida inseticida mutualismo parasitismo comensalismo competic simbiose relacoes_ecologicas bioacumul biorremedia recife coral")),
 ('Genética e Biotecnologia', L("gene genes genetic dna rna cromossom alelo heranca hereditar fenotip genotip mendel mutac transgenic clonag biotecnolog pcr dominante recessiv heterozig homozig sangue_tipo grupo_sanguineo sistema_abo fator_rh daltonism hemofil codigo_genetico transcric traduc celula-tronco celulas-tronco terapia_genica crispr marcador_molecular sequenciamento")),
 ('Citologia e Bioquímica', L("celula celular membrana mitocondri cloroplast ribossom citoplasma organela organelas mitose meiose enzima proteina metabol fotossintese respiracao_celular fermentac atp glicose lipidio carboidrato osmose difusao nucleo lisossomo complexo_golgi reticulo divisao_celular")),
 ('Corpo Humano e Saúde', L("doenca saude vacina soro imun anticorpo sistema_nervoso hormonio insulina diabetes sangue coracao pulm rim figado digest intestino estomago musculo osso pele paciente sintoma medicamento farmaco virus bacteria infecc dengue malaria zika chagas leishmaniose verminose esquistossomose protozoar parasit vetor transmissao epidemi gestac gravidez contracep anticoncepcional placenta embriao feto menstrua sexualmente obesidade nutric vitamina dieta cancer tumor anemia neuron cerebro reflexo antibiotico")),
 ('Evolução', L("evoluc evolutiv selecao_natural darwin lamarck adaptac fossil especiacao ancestral irradiacao_adaptativa convergencia origem_da_vida resistencia_a_antibiotico deriva_genetica isolamento_reprodutivo filogen")),
 ('Botânica e Zoologia', L("planta vegeta folha raiz caule flor fruto semente poliniz germinac seiva xilema floema estomato angiosperma gimnosperma briofita pteridofita fungo animal animais inseto mamifer aves peixe anfibi reptil artropode aracnideo molusco verme anelideo invertebrado vertebrado larva metamorfose abelha formiga mosquito")),
],
'quimica':[
 ('Estequiometria e Cálculos', L("massa_molar g/mol mol mols estequiometr rendimento pureza quantidade_de_materia numero_de_avogadro proporcao reagente_limitante massa_de volume_de")),
 ('Soluções e Concentração', L("solucao solucoes concentrac mol/l g/l diluic soluto solvente solubil titulac ppm propriedades_coligativas osmose pressao_de_vapor ebulioscop crioscop saturad")),
 ('Termoquímica e Cinética', L("entalpia exotermic endotermic calor_de_combustao energia_de_ligacao kj/mol kj cinetica velocidade_da_reacao velocidade_de_reacao catalis energia_de_ativacao temperatura_da_reacao")),
 ('Equilíbrio Químico e pH', L("equilibrio constante_de_equilibrio ph poh acido acida acidez base basic neutraliz tampao hidrolise_salina indicador ka kb kps le_chatelier deslocamento_do_equilibrio")),
 ('Eletroquímica', L("pilha bateria eletrolis eletrodo anodo catodo potencial_de_reducao semirreacao oxirreducao oxidac reduc corrosao galvaniz ferrugem eletroquimic oxidante redutor nox numero_de_oxidacao")),
 ('Química Orgânica', L("organic hidrocarbonet alcool eter ester cetona aldeido amina amida acido_carboxilico carboxil funcao_organica grupo_funcional cadeia_carbonica isomer benzeno aromatic polimer plastico biodiesel triglicer saponific esterific petroleo gasolina etanol metanol carbono_quiral enantiomer formula_estrutural sabao detergente")),
 ('Química Geral e Ambiental', L("atomo atomic modelo_atomico eletron isotop tabela_periodica ligacao_ionica ligacao_covalente ligacao_metalica intermolecular polaridade separacao destilac filtrac decantac mistura radioativ meia-vida chuva_acida efeito_estufa poluic tratamento_de_agua lixo reciclag combustao co2 metal metais")),
],
'geografia':[
 ('Cartografia e Geotecnologias', L("mapa mapas escala cartograf latitude longitude fuso coordenada projecao sensoriamento satelite gps imagem_de_satelite curvas_de_nivel hemisferio paralelo meridiano orientac")),
 ('Clima e Hidrografia', L("clima climatic chuva chuvas precipitac el_nino massas_de_ar umidade temperatura climograma ilha_de_calor inversao_termica aquecimento_global efeito_estufa monção moncao bacia_hidrografica rio rios aquifero hidrografi hidrologic enchente inundac seca semiarido")),
 ('Relevo, Solos e Geologia', L("relevo solo solos erosao intemperismo tectonic placas terremoto sismo vulcao geomorfolog rocha rochas mineral planalto planicie cordilheira escudo cratons crosta litosfera dobramento voragem assoreamento lixiviac laterizac desertific movimentos_de_massa deslizamento")),
 ('Urbanização e População', L("urbaniz urbano urbana cidade cidades metropol megalopole conurbac favela segregac periferi migrac migrant exodo_rural populac demografi natalidade mortalidade envelhecimento bonus_demografico mobilidade_urbana transporte_publico moradia gentrific plano_diretor refugiad")),
 ('Espaço Agrário', L("agricultur agrari agronegocio agropecuari latifundi reforma_agraria campo rural camponês campones mst soja gado pecuaria monocultura irrigac lavoura fronteira_agricola agroindustr agroecolog agrotoxic produtor_rural terra_")),
 ('Indústria, Economia e Globalização', L("industria industrial industrializ globaliz multinacional transnacional empresa empresas fordismo toyotismo taylorismo tecnologia mercado comercio exportac importac balanca_comercial logistic porto portos rodovi ferrovi infraestrutura trabalho servicos terciario desconcentrac financeir capital")),
 ('Geopolítica e Conflitos', L("geopolitic guerra_fria otan onu conselho_de_seguranca conflito conflitos fronteira territorio_palestino palestin israel bloco_economico mercosul uniao_europeia nafta acordo tratado soberania terrorismo multipolar bipolar estado_nacional nacionalismo separatis")),
 ('Meio Ambiente e Recursos', L("ambiental ambientais sustentab desmatamento biodiversidade bioma amazonia cerrado caatinga recursos_naturais energia hidreletric petroleo matriz_energetica mineracao minerio agua residuos lixo conservac unidade_de_conservacao poluic protocolo_de_quioto")),
],
}
