/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesafioRouteImport } from './routes/desafio'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as QuestoesIndexRouteImport } from './routes/questoes/index'
import { Route as QuestoesIdRouteImport } from './routes/questoes/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesafioRoute = DesafioRouteImport.update({
  id: '/desafio',
  path: '/desafio',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestoesIndexRoute = QuestoesIndexRouteImport.update({
  id: '/questoes/',
  path: '/questoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestoesIdRoute = QuestoesIdRouteImport.update({
  id: '/questoes/$id',
  path: '/questoes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/desafio': typeof DesafioRoute
  '/mapa': typeof MapaRoute
  '/perfil': typeof PerfilRoute
  '/questoes/$id': typeof QuestoesIdRoute
  '/questoes/': typeof QuestoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/desafio': typeof DesafioRoute
  '/mapa': typeof MapaRoute
  '/perfil': typeof PerfilRoute
  '/questoes/$id': typeof QuestoesIdRoute
  '/questoes': typeof QuestoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/desafio': typeof DesafioRoute
  '/mapa': typeof MapaRoute
  '/perfil': typeof PerfilRoute
  '/questoes/$id': typeof QuestoesIdRoute
  '/questoes/': typeof QuestoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/desafio' | '/mapa' | '/perfil' | '/questoes/$id' | '/questoes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/desafio' | '/mapa' | '/perfil' | '/questoes/$id' | '/questoes'
  id:
    | '__root__'
    | '/'
    | '/desafio'
    | '/mapa'
    | '/perfil'
    | '/questoes/$id'
    | '/questoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesafioRoute: typeof DesafioRoute
  MapaRoute: typeof MapaRoute
  PerfilRoute: typeof PerfilRoute
  QuestoesIdRoute: typeof QuestoesIdRoute
  QuestoesIndexRoute: typeof QuestoesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desafio': {
      id: '/desafio'
      path: '/desafio'
      fullPath: '/desafio'
      preLoaderRoute: typeof DesafioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questoes/': {
      id: '/questoes/'
      path: '/questoes'
      fullPath: '/questoes/'
      preLoaderRoute: typeof QuestoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questoes/$id': {
      id: '/questoes/$id'
      path: '/questoes/$id'
      fullPath: '/questoes/$id'
      preLoaderRoute: typeof QuestoesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesafioRoute: DesafioRoute,
  MapaRoute: MapaRoute,
  PerfilRoute: PerfilRoute,
  QuestoesIdRoute: QuestoesIdRoute,
  QuestoesIndexRoute: QuestoesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
